# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _liquid_crystal
else:
    import _liquid_crystal

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


FT_OK = _liquid_crystal.FT_OK
FT_InvalidHandle = _liquid_crystal.FT_InvalidHandle
FT_DeviceNotFound = _liquid_crystal.FT_DeviceNotFound
FT_DeviceNotOpened = _liquid_crystal.FT_DeviceNotOpened
FT_IOError = _liquid_crystal.FT_IOError
FT_InsufficientResources = _liquid_crystal.FT_InsufficientResources
FT_InvalidParameter = _liquid_crystal.FT_InvalidParameter
FT_DeviceNotPresent = _liquid_crystal.FT_DeviceNotPresent
FT_IncorrectDevice = _liquid_crystal.FT_IncorrectDevice
MOT_NotMotor = _liquid_crystal.MOT_NotMotor
MOT_DCMotor = _liquid_crystal.MOT_DCMotor
MOT_StepperMotor = _liquid_crystal.MOT_StepperMotor
MOT_BrushlessMotor = _liquid_crystal.MOT_BrushlessMotor
MOT_CustomMotor = _liquid_crystal.MOT_CustomMotor
class TLI_DeviceInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    typeID = property(_liquid_crystal.TLI_DeviceInfo_typeID_get, _liquid_crystal.TLI_DeviceInfo_typeID_set)
    description = property(_liquid_crystal.TLI_DeviceInfo_description_get, _liquid_crystal.TLI_DeviceInfo_description_set)
    serialNo = property(_liquid_crystal.TLI_DeviceInfo_serialNo_get, _liquid_crystal.TLI_DeviceInfo_serialNo_set)
    PID = property(_liquid_crystal.TLI_DeviceInfo_PID_get, _liquid_crystal.TLI_DeviceInfo_PID_set)
    isKnownType = property(_liquid_crystal.TLI_DeviceInfo_isKnownType_get, _liquid_crystal.TLI_DeviceInfo_isKnownType_set)
    motorType = property(_liquid_crystal.TLI_DeviceInfo_motorType_get, _liquid_crystal.TLI_DeviceInfo_motorType_set)
    isPiezoDevice = property(_liquid_crystal.TLI_DeviceInfo_isPiezoDevice_get, _liquid_crystal.TLI_DeviceInfo_isPiezoDevice_set)
    isLaser = property(_liquid_crystal.TLI_DeviceInfo_isLaser_get, _liquid_crystal.TLI_DeviceInfo_isLaser_set)
    isCustomType = property(_liquid_crystal.TLI_DeviceInfo_isCustomType_get, _liquid_crystal.TLI_DeviceInfo_isCustomType_set)
    isRack = property(_liquid_crystal.TLI_DeviceInfo_isRack_get, _liquid_crystal.TLI_DeviceInfo_isRack_set)
    maxChannels = property(_liquid_crystal.TLI_DeviceInfo_maxChannels_get, _liquid_crystal.TLI_DeviceInfo_maxChannels_set)

    def __init__(self):
        _liquid_crystal.TLI_DeviceInfo_swiginit(self, _liquid_crystal.new_TLI_DeviceInfo())
    __swig_destroy__ = _liquid_crystal.delete_TLI_DeviceInfo

# Register TLI_DeviceInfo in _liquid_crystal:
_liquid_crystal.TLI_DeviceInfo_swigregister(TLI_DeviceInfo)
class TLI_HardwareInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_liquid_crystal.TLI_HardwareInformation_serialNumber_get, _liquid_crystal.TLI_HardwareInformation_serialNumber_set)
    modelNumber = property(_liquid_crystal.TLI_HardwareInformation_modelNumber_get, _liquid_crystal.TLI_HardwareInformation_modelNumber_set)
    type = property(_liquid_crystal.TLI_HardwareInformation_type_get, _liquid_crystal.TLI_HardwareInformation_type_set)
    firmwareVersion = property(_liquid_crystal.TLI_HardwareInformation_firmwareVersion_get, _liquid_crystal.TLI_HardwareInformation_firmwareVersion_set)
    notes = property(_liquid_crystal.TLI_HardwareInformation_notes_get, _liquid_crystal.TLI_HardwareInformation_notes_set)
    deviceDependantData = property(_liquid_crystal.TLI_HardwareInformation_deviceDependantData_get, _liquid_crystal.TLI_HardwareInformation_deviceDependantData_set)
    hardwareVersion = property(_liquid_crystal.TLI_HardwareInformation_hardwareVersion_get, _liquid_crystal.TLI_HardwareInformation_hardwareVersion_set)
    modificationState = property(_liquid_crystal.TLI_HardwareInformation_modificationState_get, _liquid_crystal.TLI_HardwareInformation_modificationState_set)
    numChannels = property(_liquid_crystal.TLI_HardwareInformation_numChannels_get, _liquid_crystal.TLI_HardwareInformation_numChannels_set)

    def __init__(self):
        _liquid_crystal.TLI_HardwareInformation_swiginit(self, _liquid_crystal.new_TLI_HardwareInformation())
    __swig_destroy__ = _liquid_crystal.delete_TLI_HardwareInformation

# Register TLI_HardwareInformation in _liquid_crystal:
_liquid_crystal.TLI_HardwareInformation_swigregister(TLI_HardwareInformation)
class KLC_KCubeMMIParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    DisplayIntensity = property(_liquid_crystal.KLC_KCubeMMIParams_DisplayIntensity_get, _liquid_crystal.KLC_KCubeMMIParams_DisplayIntensity_set)
    DisplayTimeout = property(_liquid_crystal.KLC_KCubeMMIParams_DisplayTimeout_get, _liquid_crystal.KLC_KCubeMMIParams_DisplayTimeout_set)
    reserved = property(_liquid_crystal.KLC_KCubeMMIParams_reserved_get, _liquid_crystal.KLC_KCubeMMIParams_reserved_set)

    def __init__(self):
        _liquid_crystal.KLC_KCubeMMIParams_swiginit(self, _liquid_crystal.new_KLC_KCubeMMIParams())
    __swig_destroy__ = _liquid_crystal.delete_KLC_KCubeMMIParams

# Register KLC_KCubeMMIParams in _liquid_crystal:
_liquid_crystal.KLC_KCubeMMIParams_swigregister(KLC_KCubeMMIParams)
class KLC_Preset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Voltage = property(_liquid_crystal.KLC_Preset_Voltage_get, _liquid_crystal.KLC_Preset_Voltage_set)
    Frequency = property(_liquid_crystal.KLC_Preset_Frequency_get, _liquid_crystal.KLC_Preset_Frequency_set)

    def __init__(self):
        _liquid_crystal.KLC_Preset_swiginit(self, _liquid_crystal.new_KLC_Preset())
    __swig_destroy__ = _liquid_crystal.delete_KLC_Preset

# Register KLC_Preset in _liquid_crystal:
_liquid_crystal.KLC_Preset_swigregister(KLC_Preset)

def TLI_BuildDeviceList():
    return _liquid_crystal.TLI_BuildDeviceList()

def TLI_GetDeviceListSize():
    return _liquid_crystal.TLI_GetDeviceListSize()

def TLI_GetDeviceList(stringsReceiver):
    return _liquid_crystal.TLI_GetDeviceList(stringsReceiver)

def TLI_GetDeviceListByType(stringsReceiver, typeID):
    return _liquid_crystal.TLI_GetDeviceListByType(stringsReceiver, typeID)

def TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length):
    return _liquid_crystal.TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length)

def TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer):
    return _liquid_crystal.TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer)

def TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID):
    return _liquid_crystal.TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID)

def TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length):
    return _liquid_crystal.TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length)

def TLI_GetDeviceInfo(serialNo, info):
    return _liquid_crystal.TLI_GetDeviceInfo(serialNo, info)

def TLI_InitializeSimulations():
    return _liquid_crystal.TLI_InitializeSimulations()

def TLI_UninitializeSimulations():
    return _liquid_crystal.TLI_UninitializeSimulations()

def KLC_Open(serialNo):
    return _liquid_crystal.KLC_Open(serialNo)

def KLC_Close(serialNo):
    return _liquid_crystal.KLC_Close(serialNo)

def KLC_CheckConnection(serialNo):
    return _liquid_crystal.KLC_CheckConnection(serialNo)

def KLC_Identify(serialNo):
    return _liquid_crystal.KLC_Identify(serialNo)

def KLC_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState):
    return _liquid_crystal.KLC_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState)

def KLC_GetHardwareInfoBlock(serialNo, hardwareInfo):
    return _liquid_crystal.KLC_GetHardwareInfoBlock(serialNo, hardwareInfo)

def KLC_GetSoftwareVersion(serialNo):
    return _liquid_crystal.KLC_GetSoftwareVersion(serialNo)

def KLC_ClearMessageQueue(serialNo):
    return _liquid_crystal.KLC_ClearMessageQueue(serialNo)

def KLC_RegisterMessageCallback(serialNo, functionPointer):
    return _liquid_crystal.KLC_RegisterMessageCallback(serialNo, functionPointer)

def KLC_MessageQueueSize(serialNo):
    return _liquid_crystal.KLC_MessageQueueSize(serialNo)

def KLC_GetNextMessage(serialNo, messageType, messageID, messageData):
    return _liquid_crystal.KLC_GetNextMessage(serialNo, messageType, messageID, messageData)

def KLC_WaitForMessage(serialNo, messageType, messageID, messageData):
    return _liquid_crystal.KLC_WaitForMessage(serialNo, messageType, messageID, messageData)

def KLC_StartPolling(serialNo, milliseconds):
    return _liquid_crystal.KLC_StartPolling(serialNo, milliseconds)

def KLC_PollingDuration(serialNo):
    return _liquid_crystal.KLC_PollingDuration(serialNo)

def KLC_StopPolling(serialNo):
    return _liquid_crystal.KLC_StopPolling(serialNo)

def KLC_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS):
    return _liquid_crystal.KLC_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS)

def KLC_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout):
    return _liquid_crystal.KLC_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout)

def KLC_HasLastMsgTimerOverrun(serialNo):
    return _liquid_crystal.KLC_HasLastMsgTimerOverrun(serialNo)

def KLC_RequestSettings(serialNo):
    return _liquid_crystal.KLC_RequestSettings(serialNo)

def KLC_LoadSettings(serialNo):
    return _liquid_crystal.KLC_LoadSettings(serialNo)

def KLC_LoadNamedSettings(serialNo, settingsName):
    return _liquid_crystal.KLC_LoadNamedSettings(serialNo, settingsName)

def KLC_PersistSettings(serialNo):
    return _liquid_crystal.KLC_PersistSettings(serialNo)

