# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _position_aligner
else:
    import _position_aligner

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


FT_OK = _position_aligner.FT_OK
FT_InvalidHandle = _position_aligner.FT_InvalidHandle
FT_DeviceNotFound = _position_aligner.FT_DeviceNotFound
FT_DeviceNotOpened = _position_aligner.FT_DeviceNotOpened
FT_IOError = _position_aligner.FT_IOError
FT_InsufficientResources = _position_aligner.FT_InsufficientResources
FT_InvalidParameter = _position_aligner.FT_InvalidParameter
FT_DeviceNotPresent = _position_aligner.FT_DeviceNotPresent
FT_IncorrectDevice = _position_aligner.FT_IncorrectDevice
MOT_NotMotor = _position_aligner.MOT_NotMotor
MOT_DCMotor = _position_aligner.MOT_DCMotor
MOT_StepperMotor = _position_aligner.MOT_StepperMotor
MOT_BrushlessMotor = _position_aligner.MOT_BrushlessMotor
MOT_CustomMotor = _position_aligner.MOT_CustomMotor
QD_ModeUndefined = _position_aligner.QD_ModeUndefined
QD_Monitor = _position_aligner.QD_Monitor
QD_OpenLoop = _position_aligner.QD_OpenLoop
QD_ClosedLoop = _position_aligner.QD_ClosedLoop
QD_AutoOpenClosedLoop = _position_aligner.QD_AutoOpenClosedLoop
QD_RouteUndefined = _position_aligner.QD_RouteUndefined
QD_SMAOnly = _position_aligner.QD_SMAOnly
QD_HubAndSMA = _position_aligner.QD_HubAndSMA
QD_HoldOnZero = _position_aligner.QD_HoldOnZero
QD_HoldOnLastValue = _position_aligner.QD_HoldOnLastValue
QD_Undefined = _position_aligner.QD_Undefined
QD_Enabled = _position_aligner.QD_Enabled
QD_Disabled = _position_aligner.QD_Disabled
class TLI_DeviceInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    typeID = property(_position_aligner.TLI_DeviceInfo_typeID_get, _position_aligner.TLI_DeviceInfo_typeID_set)
    description = property(_position_aligner.TLI_DeviceInfo_description_get, _position_aligner.TLI_DeviceInfo_description_set)
    serialNo = property(_position_aligner.TLI_DeviceInfo_serialNo_get, _position_aligner.TLI_DeviceInfo_serialNo_set)
    PID = property(_position_aligner.TLI_DeviceInfo_PID_get, _position_aligner.TLI_DeviceInfo_PID_set)
    isKnownType = property(_position_aligner.TLI_DeviceInfo_isKnownType_get, _position_aligner.TLI_DeviceInfo_isKnownType_set)
    motorType = property(_position_aligner.TLI_DeviceInfo_motorType_get, _position_aligner.TLI_DeviceInfo_motorType_set)
    isPiezoDevice = property(_position_aligner.TLI_DeviceInfo_isPiezoDevice_get, _position_aligner.TLI_DeviceInfo_isPiezoDevice_set)
    isLaser = property(_position_aligner.TLI_DeviceInfo_isLaser_get, _position_aligner.TLI_DeviceInfo_isLaser_set)
    isCustomType = property(_position_aligner.TLI_DeviceInfo_isCustomType_get, _position_aligner.TLI_DeviceInfo_isCustomType_set)
    isRack = property(_position_aligner.TLI_DeviceInfo_isRack_get, _position_aligner.TLI_DeviceInfo_isRack_set)
    maxChannels = property(_position_aligner.TLI_DeviceInfo_maxChannels_get, _position_aligner.TLI_DeviceInfo_maxChannels_set)

    def __init__(self):
        _position_aligner.TLI_DeviceInfo_swiginit(self, _position_aligner.new_TLI_DeviceInfo())
    __swig_destroy__ = _position_aligner.delete_TLI_DeviceInfo

# Register TLI_DeviceInfo in _position_aligner:
_position_aligner.TLI_DeviceInfo_swigregister(TLI_DeviceInfo)
class TLI_HardwareInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_position_aligner.TLI_HardwareInformation_serialNumber_get, _position_aligner.TLI_HardwareInformation_serialNumber_set)
    modelNumber = property(_position_aligner.TLI_HardwareInformation_modelNumber_get, _position_aligner.TLI_HardwareInformation_modelNumber_set)
    type = property(_position_aligner.TLI_HardwareInformation_type_get, _position_aligner.TLI_HardwareInformation_type_set)
    firmwareVersion = property(_position_aligner.TLI_HardwareInformation_firmwareVersion_get, _position_aligner.TLI_HardwareInformation_firmwareVersion_set)
    notes = property(_position_aligner.TLI_HardwareInformation_notes_get, _position_aligner.TLI_HardwareInformation_notes_set)
    deviceDependantData = property(_position_aligner.TLI_HardwareInformation_deviceDependantData_get, _position_aligner.TLI_HardwareInformation_deviceDependantData_set)
    hardwareVersion = property(_position_aligner.TLI_HardwareInformation_hardwareVersion_get, _position_aligner.TLI_HardwareInformation_hardwareVersion_set)
    modificationState = property(_position_aligner.TLI_HardwareInformation_modificationState_get, _position_aligner.TLI_HardwareInformation_modificationState_set)
    numChannels = property(_position_aligner.TLI_HardwareInformation_numChannels_get, _position_aligner.TLI_HardwareInformation_numChannels_set)

    def __init__(self):
        _position_aligner.TLI_HardwareInformation_swiginit(self, _position_aligner.new_TLI_HardwareInformation())
    __swig_destroy__ = _position_aligner.delete_TLI_HardwareInformation

# Register TLI_HardwareInformation in _position_aligner:
_position_aligner.TLI_HardwareInformation_swigregister(TLI_HardwareInformation)
class QD_LoopParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    proportionalGain = property(_position_aligner.QD_LoopParameters_proportionalGain_get, _position_aligner.QD_LoopParameters_proportionalGain_set)
    integralGain = property(_position_aligner.QD_LoopParameters_integralGain_get, _position_aligner.QD_LoopParameters_integralGain_set)
    differentialGain = property(_position_aligner.QD_LoopParameters_differentialGain_get, _position_aligner.QD_LoopParameters_differentialGain_set)
    lowPassFilterCutOffFreq = property(_position_aligner.QD_LoopParameters_lowPassFilterCutOffFreq_get, _position_aligner.QD_LoopParameters_lowPassFilterCutOffFreq_set)
    notchFilterCenterFrequency = property(_position_aligner.QD_LoopParameters_notchFilterCenterFrequency_get, _position_aligner.QD_LoopParameters_notchFilterCenterFrequency_set)
    notchFilterQ = property(_position_aligner.QD_LoopParameters_notchFilterQ_get, _position_aligner.QD_LoopParameters_notchFilterQ_set)
    notchFilterEnabled = property(_position_aligner.QD_LoopParameters_notchFilterEnabled_get, _position_aligner.QD_LoopParameters_notchFilterEnabled_set)
    lowPassFilterEnabled = property(_position_aligner.QD_LoopParameters_lowPassFilterEnabled_get, _position_aligner.QD_LoopParameters_lowPassFilterEnabled_set)

    def __init__(self):
        _position_aligner.QD_LoopParameters_swiginit(self, _position_aligner.new_QD_LoopParameters())
    __swig_destroy__ = _position_aligner.delete_QD_LoopParameters

# Register QD_LoopParameters in _position_aligner:
_position_aligner.QD_LoopParameters_swigregister(QD_LoopParameters)
class QD_PIDParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    proportionalGain = property(_position_aligner.QD_PIDParameters_proportionalGain_get, _position_aligner.QD_PIDParameters_proportionalGain_set)
    integralGain = property(_position_aligner.QD_PIDParameters_integralGain_get, _position_aligner.QD_PIDParameters_integralGain_set)
    differentialGain = property(_position_aligner.QD_PIDParameters_differentialGain_get, _position_aligner.QD_PIDParameters_differentialGain_set)

    def __init__(self):
        _position_aligner.QD_PIDParameters_swiginit(self, _position_aligner.new_QD_PIDParameters())
    __swig_destroy__ = _position_aligner.delete_QD_PIDParameters

# Register QD_PIDParameters in _position_aligner:
_position_aligner.QD_PIDParameters_swigregister(QD_PIDParameters)
class QD_LowPassFilterParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lowPassFilterCutOffFreq = property(_position_aligner.QD_LowPassFilterParameters_lowPassFilterCutOffFreq_get, _position_aligner.QD_LowPassFilterParameters_lowPassFilterCutOffFreq_set)
    lowPassFilterEnabled = property(_position_aligner.QD_LowPassFilterParameters_lowPassFilterEnabled_get, _position_aligner.QD_LowPassFilterParameters_lowPassFilterEnabled_set)

    def __init__(self):
        _position_aligner.QD_LowPassFilterParameters_swiginit(self, _position_aligner.new_QD_LowPassFilterParameters())
    __swig_destroy__ = _position_aligner.delete_QD_LowPassFilterParameters

# Register QD_LowPassFilterParameters in _position_aligner:
_position_aligner.QD_LowPassFilterParameters_swigregister(QD_LowPassFilterParameters)
class QD_NotchFilterParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    notchFilterCenterFrequency = property(_position_aligner.QD_NotchFilterParameters_notchFilterCenterFrequency_get, _position_aligner.QD_NotchFilterParameters_notchFilterCenterFrequency_set)
    notchFilterQ = property(_position_aligner.QD_NotchFilterParameters_notchFilterQ_get, _position_aligner.QD_NotchFilterParameters_notchFilterQ_set)
    notchFilterEnabled = property(_position_aligner.QD_NotchFilterParameters_notchFilterEnabled_get, _position_aligner.QD_NotchFilterParameters_notchFilterEnabled_set)

    def __init__(self):
        _position_aligner.QD_NotchFilterParameters_swiginit(self, _position_aligner.new_QD_NotchFilterParameters())
    __swig_destroy__ = _position_aligner.delete_QD_NotchFilterParameters

# Register QD_NotchFilterParameters in _position_aligner:
_position_aligner.QD_NotchFilterParameters_swigregister(QD_NotchFilterParameters)
class QD_PositionDemandParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    minXdemand = property(_position_aligner.QD_PositionDemandParameters_minXdemand_get, _position_aligner.QD_PositionDemandParameters_minXdemand_set)
    minYdemand = property(_position_aligner.QD_PositionDemandParameters_minYdemand_get, _position_aligner.QD_PositionDemandParameters_minYdemand_set)
    maxXdemand = property(_position_aligner.QD_PositionDemandParameters_maxXdemand_get, _position_aligner.QD_PositionDemandParameters_maxXdemand_set)
    maxYdemand = property(_position_aligner.QD_PositionDemandParameters_maxYdemand_get, _position_aligner.QD_PositionDemandParameters_maxYdemand_set)
    lowVoltageOutputRoute = property(_position_aligner.QD_PositionDemandParameters_lowVoltageOutputRoute_get, _position_aligner.QD_PositionDemandParameters_lowVoltageOutputRoute_set)
    openLoopOption = property(_position_aligner.QD_PositionDemandParameters_openLoopOption_get, _position_aligner.QD_PositionDemandParameters_openLoopOption_set)
    xFeedbackSignedGain = property(_position_aligner.QD_PositionDemandParameters_xFeedbackSignedGain_get, _position_aligner.QD_PositionDemandParameters_xFeedbackSignedGain_set)
    yFeedbackSignedGain = property(_position_aligner.QD_PositionDemandParameters_yFeedbackSignedGain_get, _position_aligner.QD_PositionDemandParameters_yFeedbackSignedGain_set)

    def __init__(self):
        _position_aligner.QD_PositionDemandParameters_swiginit(self, _position_aligner.new_QD_PositionDemandParameters())
    __swig_destroy__ = _position_aligner.delete_QD_PositionDemandParameters

# Register QD_PositionDemandParameters in _position_aligner:
_position_aligner.QD_PositionDemandParameters_swigregister(QD_PositionDemandParameters)
class QD_Position(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_position_aligner.QD_Position_x_get, _position_aligner.QD_Position_x_set)
    y = property(_position_aligner.QD_Position_y_get, _position_aligner.QD_Position_y_set)

    def __init__(self):
        _position_aligner.QD_Position_swiginit(self, _position_aligner.new_QD_Position())
    __swig_destroy__ = _position_aligner.delete_QD_Position

# Register QD_Position in _position_aligner:
_position_aligner.QD_Position_swigregister(QD_Position)
class QD_Readings(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    posDifference = property(_position_aligner.QD_Readings_posDifference_get, _position_aligner.QD_Readings_posDifference_set)
    sum = property(_position_aligner.QD_Readings_sum_get, _position_aligner.QD_Readings_sum_set)
    demandedPos = property(_position_aligner.QD_Readings_demandedPos_get, _position_aligner.QD_Readings_demandedPos_set)

    def __init__(self):
        _position_aligner.QD_Readings_swiginit(self, _position_aligner.new_QD_Readings())
    __swig_destroy__ = _position_aligner.delete_QD_Readings

# Register QD_Readings in _position_aligner:
_position_aligner.QD_Readings_swigregister(QD_Readings)
QD_Trig_Disabled = _position_aligner.QD_Trig_Disabled
QD_TrigIn_GPI = _position_aligner.QD_TrigIn_GPI
QD_TrigIn_LoopOpenClose = _position_aligner.QD_TrigIn_LoopOpenClose
KD_TrigOut_GPO = _position_aligner.KD_TrigOut_GPO
KD_TrigOut_Sum = _position_aligner.KD_TrigOut_Sum
KD_TrigOut_Diff = _position_aligner.KD_TrigOut_Diff
KD_TrigOut_SumDiff = _position_aligner.KD_TrigOut_SumDiff
GD_Trig_High = _position_aligner.GD_Trig_High
GD_Trig_Low = _position_aligner.GD_Trig_Low
class QD_KPA_TrigIOConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    trig1Mode = property(_position_aligner.QD_KPA_TrigIOConfig_trig1Mode_get, _position_aligner.QD_KPA_TrigIOConfig_trig1Mode_set)
    trig1Polarity = property(_position_aligner.QD_KPA_TrigIOConfig_trig1Polarity_get, _position_aligner.QD_KPA_TrigIOConfig_trig1Polarity_set)
    trig1SumMin = property(_position_aligner.QD_KPA_TrigIOConfig_trig1SumMin_get, _position_aligner.QD_KPA_TrigIOConfig_trig1SumMin_set)
    trig1SumMax = property(_position_aligner.QD_KPA_TrigIOConfig_trig1SumMax_get, _position_aligner.QD_KPA_TrigIOConfig_trig1SumMax_set)
    trig1DiffThreshold = property(_position_aligner.QD_KPA_TrigIOConfig_trig1DiffThreshold_get, _position_aligner.QD_KPA_TrigIOConfig_trig1DiffThreshold_set)
    trig2Mode = property(_position_aligner.QD_KPA_TrigIOConfig_trig2Mode_get, _position_aligner.QD_KPA_TrigIOConfig_trig2Mode_set)
    trig2Polarity = property(_position_aligner.QD_KPA_TrigIOConfig_trig2Polarity_get, _position_aligner.QD_KPA_TrigIOConfig_trig2Polarity_set)
    trig2SumMin = property(_position_aligner.QD_KPA_TrigIOConfig_trig2SumMin_get, _position_aligner.QD_KPA_TrigIOConfig_trig2SumMin_set)
    trig2SumMax = property(_position_aligner.QD_KPA_TrigIOConfig_trig2SumMax_get, _position_aligner.QD_KPA_TrigIOConfig_trig2SumMax_set)
    trig2DiffThreshold = property(_position_aligner.QD_KPA_TrigIOConfig_trig2DiffThreshold_get, _position_aligner.QD_KPA_TrigIOConfig_trig2DiffThreshold_set)
    wReserved = property(_position_aligner.QD_KPA_TrigIOConfig_wReserved_get, _position_aligner.QD_KPA_TrigIOConfig_wReserved_set)

    def __init__(self):
        _position_aligner.QD_KPA_TrigIOConfig_swiginit(self, _position_aligner.new_QD_KPA_TrigIOConfig())
    __swig_destroy__ = _position_aligner.delete_QD_KPA_TrigIOConfig

# Register QD_KPA_TrigIOConfig in _position_aligner:
_position_aligner.QD_KPA_TrigIOConfig_swigregister(QD_KPA_TrigIOConfig)
class QD_KPA_DigitalIO(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    wDigOPs = property(_position_aligner.QD_KPA_DigitalIO_wDigOPs_get, _position_aligner.QD_KPA_DigitalIO_wDigOPs_set)
    wReserved = property(_position_aligner.QD_KPA_DigitalIO_wReserved_get, _position_aligner.QD_KPA_DigitalIO_wReserved_set)

    def __init__(self):
        _position_aligner.QD_KPA_DigitalIO_swiginit(self, _position_aligner.new_QD_KPA_DigitalIO())
    __swig_destroy__ = _position_aligner.delete_QD_KPA_DigitalIO

# Register QD_KPA_DigitalIO in _position_aligner:
_position_aligner.QD_KPA_DigitalIO_swigregister(QD_KPA_DigitalIO)
class QD_ClosedLoopPosition(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_position_aligner.QD_ClosedLoopPosition_x_get, _position_aligner.QD_ClosedLoopPosition_x_set)
    y = property(_position_aligner.QD_ClosedLoopPosition_y_get, _position_aligner.QD_ClosedLoopPosition_y_set)

    def __init__(self):
        _position_aligner.QD_ClosedLoopPosition_swiginit(self, _position_aligner.new_QD_ClosedLoopPosition())
    __swig_destroy__ = _position_aligner.delete_QD_ClosedLoopPosition

# Register QD_ClosedLoopPosition in _position_aligner:
_position_aligner.QD_ClosedLoopPosition_swigregister(QD_ClosedLoopPosition)

def TLI_BuildDeviceList():
    return _position_aligner.TLI_BuildDeviceList()

def TLI_GetDeviceListSize():
    return _position_aligner.TLI_GetDeviceListSize()

def TLI_GetDeviceList(stringsReceiver):
    return _position_aligner.TLI_GetDeviceList(stringsReceiver)

def TLI_GetDeviceListByType(stringsReceiver, typeID):
    return _position_aligner.TLI_GetDeviceListByType(stringsReceiver, typeID)

def TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length):
    return _position_aligner.TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length)

def TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer):
    return _position_aligner.TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer)

def TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID):
    return _position_aligner.TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID)

def TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length):
    return _position_aligner.TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length)

def TLI_GetDeviceInfo(serialNo, info):
    return _position_aligner.TLI_GetDeviceInfo(serialNo, info)

def TLI_InitializeSimulations():
    return _position_aligner.TLI_InitializeSimulations()

def TLI_UninitializeSimulations():
    return _position_aligner.TLI_UninitializeSimulations()

def QD_Open(serialNo):
    return _position_aligner.QD_Open(serialNo)

def QD_Close(serialNo):
    return _position_aligner.QD_Close(serialNo)

def QD_CheckConnection(serialNo):
    return _position_aligner.QD_CheckConnection(serialNo)

def QD_CanDeviceLockFrontPanel(serialNo):
    return _position_aligner.QD_CanDeviceLockFrontPanel(serialNo)

def QD_GetFrontPanelLocked(serialNo):
    return _position_aligner.QD_GetFrontPanelLocked(serialNo)

def QD_RequestFrontPanelLocked(serialNo):
    return _position_aligner.QD_RequestFrontPanelLocked(serialNo)

def QD_SetFrontPanelLock(serialNo, locked):
    return _position_aligner.QD_SetFrontPanelLock(serialNo, locked)

def QD_Identify(serialNo):
    return _position_aligner.QD_Identify(serialNo)

def QD_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState):
    return _position_aligner.QD_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState)

def QD_GetHardwareInfoBlock(serialNo, hardwareInfo):
    return _position_aligner.QD_GetHardwareInfoBlock(serialNo, hardwareInfo)

def QD_GetFirmwareVersion(serialNo):
    return _position_aligner.QD_GetFirmwareVersion(serialNo)

def QD_GetSoftwareVersion(serialNo):
    return _position_aligner.QD_GetSoftwareVersion(serialNo)

def QD_LoadSettings(serialNo):
    return _position_aligner.QD_LoadSettings(serialNo)

def QD_LoadNamedSettings(serialNo, settingsName):
    return _position_aligner.QD_LoadNamedSettings(serialNo, settingsName)

def QD_PersistSettings(serialNo):
    return _position_aligner.QD_PersistSettings(serialNo)

def QD_ClearMessageQueue(serialNo):
    return _position_aligner.QD_ClearMessageQueue(serialNo)

def QD_RegisterMessageCallback(serialNo, functionPointer):
    return _position_aligner.QD_RegisterMessageCallback(serialNo, functionPointer)

def QD_MessageQueueSize(serialNo):
    return _position_aligner.QD_MessageQueueSize(serialNo)

def QD_GetNextMessage(serialNo, messageType, messageID, messageData):
    return _position_aligner.QD_GetNextMessage(serialNo, messageType, messageID, messageData)

def QD_WaitForMessage(serialNo, messageType, messageID, messageData):
    return _position_aligner.QD_WaitForMessage(serialNo, messageType, messageID, messageData)

def QD_RequestLoopPIDparams(serialNo):
    return _position_aligner.QD_RequestLoopPIDparams(serialNo)

def QD_GetLoopPIDparams(serialNo, loopParams):
    return _position_aligner.QD_GetLoopPIDparams(serialNo, loopParams)

def QD_SetLoopPIDparams(serialNo, loopParams):
    return _position_aligner.QD_SetLoopPIDparams(serialNo, loopParams)

def QD_GetPIDparams(serialNo, proportionalIntegralDerivativeParams):
    return _position_aligner.QD_GetPIDparams(serialNo, proportionalIntegralDerivativeParams)

def QD_SetPIDparams(serialNo, proportionalIntegralDerivativeParams):
    return _position_aligner.QD_SetPIDparams(serialNo, proportionalIntegralDerivativeParams)

def QD_GetLowPassFilterparams(serialNo, lowPassParams):
    return _position_aligner.QD_GetLowPassFilterparams(serialNo, lowPassParams)

def QD_SetLowPassFilterparams(serialNo, lowPassParams):
    return _position_aligner.QD_SetLowPassFilterparams(serialNo, lowPassParams)

def QD_GetNotchFilterparams(serialNo, notchParams):
    return _position_aligner.QD_GetNotchFilterparams(serialNo, notchParams)

def QD_SetNotchFilterparams(serialNo, proportionalIntegralDerivativeParams):
    return _position_aligner.QD_SetNotchFilterparams(serialNo, proportionalIntegralDerivativeParams)

def QD_RequestPosDemandParams(serialNo):
    return _position_aligner.QD_RequestPosDemandParams(serialNo)

def QD_GetPosDemandParams(serialNo, demandParams):
    return _position_aligner.QD_GetPosDemandParams(serialNo, demandParams)

def QD_SetPosDemandParams(serialNo, demandParams):
    return _position_aligner.QD_SetPosDemandParams(serialNo, demandParams)

def QD_RequestTriggerConfigParams(serialNo):
    return _position_aligner.QD_RequestTriggerConfigParams(serialNo)

def QD_GetTriggerConfigParams(serialNo, triggerParams):
    return _position_aligner.QD_GetTriggerConfigParams(serialNo, triggerParams)

def QD_SetTriggerConfigParams(serialNo, triggerParams):
    return _position_aligner.QD_SetTriggerConfigParams(serialNo, triggerParams)

def QD_RequestDigitalOutput(serialNo):
    return _position_aligner.QD_RequestDigitalOutput(serialNo)

def QD_SetDigitalOutput(serialNo, digitalIO):
    return _position_aligner.QD_SetDigitalOutput(serialNo, digitalIO)

def QD_GetDigitalOutput(serialNo, digitalIO):
    return _position_aligner.QD_GetDigitalOutput(serialNo, digitalIO)

def QD_RequestOperatingMode(serialNo):
    return _position_aligner.QD_RequestOperatingMode(serialNo)

def QD_GetOperatingMode(serialNo):
    return _position_aligner.QD_GetOperatingMode(serialNo)

def QD_SetOperatingMode(serialNo, mode, autoOpenCloseLoop):
    return _position_aligner.QD_SetOperatingMode(serialNo, mode, autoOpenCloseLoop)

def QD_RequestLEDBrightness(serialNo):
    return _position_aligner.QD_RequestLEDBrightness(serialNo)

def QD_GetLEDBrightness(serialNo):
    return _position_aligner.QD_GetLEDBrightness(serialNo)

def QD_SetLEDBrightness(serialNo, brightness):
    return _position_aligner.QD_SetLEDBrightness(serialNo, brightness)

def QD_GetDemandedPosition(serialNo, position):
    return _position_aligner.QD_GetDemandedPosition(serialNo, position)

def QD_SetPosition(serialNo, position):
    return _position_aligner.QD_SetPosition(serialNo, position)

def QD_GetClosedLoopPosition(serialNo, position):
    return _position_aligner.QD_GetClosedLoopPosition(serialNo, position)

def QD_SetClosedLoopPosition(serialNo, position):
    return _position_aligner.QD_SetClosedLoopPosition(serialNo, position)

def QD_RequestClosedLoopPosition(serialNo):
    return _position_aligner.QD_RequestClosedLoopPosition(serialNo)

def QD_RequestStatus(serialNo):
    return _position_aligner.QD_RequestStatus(serialNo)

def QD_RequestReading(serialNo):
    return _position_aligner.QD_RequestReading(serialNo)

def QD_RequestStatusBits(serialNo):
    return _position_aligner.QD_RequestStatusBits(serialNo)

def QD_GetReading(serialNo, reading):
    return _position_aligner.QD_GetReading(serialNo, reading)

def QD_GetStatusBits(serialNo):
    return _position_aligner.QD_GetStatusBits(serialNo)

def QD_StartPolling(serialNo, milliseconds):
    return _position_aligner.QD_StartPolling(serialNo, milliseconds)

def QD_PollingDuration(serialNo):
    return _position_aligner.QD_PollingDuration(serialNo)

def QD_StopPolling(serialNo):
    return _position_aligner.QD_StopPolling(serialNo)

def QD_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS):
    return _position_aligner.QD_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS)

def QD_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout):
    return _position_aligner.QD_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout)

def QD_HasLastMsgTimerOverrun(serialNo):
    return _position_aligner.QD_HasLastMsgTimerOverrun(serialNo)

def QD_RequestSettings(serialNo):
    return _position_aligner.QD_RequestSettings(serialNo)

