# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _tec
else:
    import _tec

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


FT_OK = _tec.FT_OK
FT_InvalidHandle = _tec.FT_InvalidHandle
FT_DeviceNotFound = _tec.FT_DeviceNotFound
FT_DeviceNotOpened = _tec.FT_DeviceNotOpened
FT_IOError = _tec.FT_IOError
FT_InsufficientResources = _tec.FT_InsufficientResources
FT_InvalidParameter = _tec.FT_InvalidParameter
FT_DeviceNotPresent = _tec.FT_DeviceNotPresent
FT_IncorrectDevice = _tec.FT_IncorrectDevice
MOT_NotMotor = _tec.MOT_NotMotor
MOT_DCMotor = _tec.MOT_DCMotor
MOT_StepperMotor = _tec.MOT_StepperMotor
MOT_BrushlessMotor = _tec.MOT_BrushlessMotor
MOT_CustomMotor = _tec.MOT_CustomMotor
class TC_LoopParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    proportionalGain = property(_tec.TC_LoopParameters_proportionalGain_get, _tec.TC_LoopParameters_proportionalGain_set)
    integralGain = property(_tec.TC_LoopParameters_integralGain_get, _tec.TC_LoopParameters_integralGain_set)
    differentialGain = property(_tec.TC_LoopParameters_differentialGain_get, _tec.TC_LoopParameters_differentialGain_set)

    def __init__(self):
        _tec.TC_LoopParameters_swiginit(self, _tec.new_TC_LoopParameters())
    __swig_destroy__ = _tec.delete_TC_LoopParameters

# Register TC_LoopParameters in _tec:
_tec.TC_LoopParameters_swigregister(TC_LoopParameters)
TC_Transducer = _tec.TC_Transducer
TC_TH20kOhm = _tec.TC_TH20kOhm
TC_TH200kOhm = _tec.TC_TH200kOhm
TC_ActualTemperature = _tec.TC_ActualTemperature
TC_TargetTemperature = _tec.TC_TargetTemperature
TC_TempDifference = _tec.TC_TempDifference
TC_Current = _tec.TC_Current
class TLI_DeviceInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    typeID = property(_tec.TLI_DeviceInfo_typeID_get, _tec.TLI_DeviceInfo_typeID_set)
    description = property(_tec.TLI_DeviceInfo_description_get, _tec.TLI_DeviceInfo_description_set)
    serialNo = property(_tec.TLI_DeviceInfo_serialNo_get, _tec.TLI_DeviceInfo_serialNo_set)
    PID = property(_tec.TLI_DeviceInfo_PID_get, _tec.TLI_DeviceInfo_PID_set)
    isKnownType = property(_tec.TLI_DeviceInfo_isKnownType_get, _tec.TLI_DeviceInfo_isKnownType_set)
    motorType = property(_tec.TLI_DeviceInfo_motorType_get, _tec.TLI_DeviceInfo_motorType_set)
    isPiezoDevice = property(_tec.TLI_DeviceInfo_isPiezoDevice_get, _tec.TLI_DeviceInfo_isPiezoDevice_set)
    isLaser = property(_tec.TLI_DeviceInfo_isLaser_get, _tec.TLI_DeviceInfo_isLaser_set)
    isCustomType = property(_tec.TLI_DeviceInfo_isCustomType_get, _tec.TLI_DeviceInfo_isCustomType_set)
    isRack = property(_tec.TLI_DeviceInfo_isRack_get, _tec.TLI_DeviceInfo_isRack_set)
    maxChannels = property(_tec.TLI_DeviceInfo_maxChannels_get, _tec.TLI_DeviceInfo_maxChannels_set)

    def __init__(self):
        _tec.TLI_DeviceInfo_swiginit(self, _tec.new_TLI_DeviceInfo())
    __swig_destroy__ = _tec.delete_TLI_DeviceInfo

# Register TLI_DeviceInfo in _tec:
_tec.TLI_DeviceInfo_swigregister(TLI_DeviceInfo)
class TLI_HardwareInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_tec.TLI_HardwareInformation_serialNumber_get, _tec.TLI_HardwareInformation_serialNumber_set)
    modelNumber = property(_tec.TLI_HardwareInformation_modelNumber_get, _tec.TLI_HardwareInformation_modelNumber_set)
    type = property(_tec.TLI_HardwareInformation_type_get, _tec.TLI_HardwareInformation_type_set)
    firmwareVersion = property(_tec.TLI_HardwareInformation_firmwareVersion_get, _tec.TLI_HardwareInformation_firmwareVersion_set)
    notes = property(_tec.TLI_HardwareInformation_notes_get, _tec.TLI_HardwareInformation_notes_set)
    deviceDependantData = property(_tec.TLI_HardwareInformation_deviceDependantData_get, _tec.TLI_HardwareInformation_deviceDependantData_set)
    hardwareVersion = property(_tec.TLI_HardwareInformation_hardwareVersion_get, _tec.TLI_HardwareInformation_hardwareVersion_set)
    modificationState = property(_tec.TLI_HardwareInformation_modificationState_get, _tec.TLI_HardwareInformation_modificationState_set)
    numChannels = property(_tec.TLI_HardwareInformation_numChannels_get, _tec.TLI_HardwareInformation_numChannels_set)

    def __init__(self):
        _tec.TLI_HardwareInformation_swiginit(self, _tec.new_TLI_HardwareInformation())
    __swig_destroy__ = _tec.delete_TLI_HardwareInformation

# Register TLI_HardwareInformation in _tec:
_tec.TLI_HardwareInformation_swigregister(TLI_HardwareInformation)

def TLI_BuildDeviceList():
    return _tec.TLI_BuildDeviceList()

def TLI_GetDeviceListSize():
    return _tec.TLI_GetDeviceListSize()

def TLI_GetDeviceList(stringsReceiver):
    return _tec.TLI_GetDeviceList(stringsReceiver)

def TLI_GetDeviceListByType(stringsReceiver, typeID):
    return _tec.TLI_GetDeviceListByType(stringsReceiver, typeID)

def TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length):
    return _tec.TLI_GetDeviceListByTypes(stringsReceiver, typeIDs, length)

def TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer):
    return _tec.TLI_GetDeviceListExt(receiveBuffer, sizeOfBuffer)

def TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID):
    return _tec.TLI_GetDeviceListByTypeExt(receiveBuffer, sizeOfBuffer, typeID)

def TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length):
    return _tec.TLI_GetDeviceListByTypesExt(receiveBuffer, sizeOfBuffer, typeIDs, length)

def TLI_GetDeviceInfo(serialNo, info):
    return _tec.TLI_GetDeviceInfo(serialNo, info)

def TLI_InitializeSimulations():
    return _tec.TLI_InitializeSimulations()

def TLI_UninitializeSimulations():
    return _tec.TLI_UninitializeSimulations()

def TC_Open(serialNo):
    return _tec.TC_Open(serialNo)

def TC_Close(serialNo):
    return _tec.TC_Close(serialNo)

def TC_CheckConnection(serialNo):
    return _tec.TC_CheckConnection(serialNo)

def TC_Identify(serialNo):
    return _tec.TC_Identify(serialNo)

def TC_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState):
    return _tec.TC_GetHardwareInfo(serialNo, modelNo, sizeOfModelNo, type, numChannels, notes, sizeOfNotes, firmwareVersion, hardwareVersion, modificationState)

def TC_GetHardwareInfoBlock(serialNo, hardwareInfo):
    return _tec.TC_GetHardwareInfoBlock(serialNo, hardwareInfo)

def TC_GetFirmwareVersion(serialNo):
    return _tec.TC_GetFirmwareVersion(serialNo)

def TC_GetSoftwareVersion(serialNo):
    return _tec.TC_GetSoftwareVersion(serialNo)

def TC_LoadSettings(serialNo):
    return _tec.TC_LoadSettings(serialNo)

def TC_LoadNamedSettings(serialNo, settingsName):
    return _tec.TC_LoadNamedSettings(serialNo, settingsName)

def TC_PersistSettings(serialNo):
    return _tec.TC_PersistSettings(serialNo)

def TC_Disable(serialNo):
    return _tec.TC_Disable(serialNo)

def TC_Enable(serialNo):
    return _tec.TC_Enable(serialNo)

def TC_Reset(serialNo):
    return _tec.TC_Reset(serialNo)

def TC_Disconnect(serialNo):
    return _tec.TC_Disconnect(serialNo)

def TC_ClearMessageQueue(serialNo):
    return _tec.TC_ClearMessageQueue(serialNo)

def TC_RegisterMessageCallback(serialNo, functionPointer):
    return _tec.TC_RegisterMessageCallback(serialNo, functionPointer)

def TC_MessageQueueSize(serialNo):
    return _tec.TC_MessageQueueSize(serialNo)

def TC_GetNextMessage(serialNo, messageType, messageID, messageData):
    return _tec.TC_GetNextMessage(serialNo, messageType, messageID, messageData)

def TC_WaitForMessage(serialNo, messageType, messageID, messageData):
    return _tec.TC_WaitForMessage(serialNo, messageType, messageID, messageData)

def TC_RequestTemperatureSet(serialNo):
    return _tec.TC_RequestTemperatureSet(serialNo)

def TC_GetTemperatureSet(serialNo):
    return _tec.TC_GetTemperatureSet(serialNo)

def TC_SetTemperature(serialNo, temperature):
    return _tec.TC_SetTemperature(serialNo, temperature)

def TC_RequestHWDisplayMode(serialNo):
    return _tec.TC_RequestHWDisplayMode(serialNo)

def TC_GetHWDisplayMode(serialNo):
    return _tec.TC_GetHWDisplayMode(serialNo)

def TC_SetHWDisplayMode(serialNo, mode):
    return _tec.TC_SetHWDisplayMode(serialNo, mode)

def TC_RequestLEDBrightness(serialNo):
    return _tec.TC_RequestLEDBrightness(serialNo)

def TC_GetLEDBrightness(serialNo):
    return _tec.TC_GetLEDBrightness(serialNo)

def TC_SetLEDBrightness(serialNo, brightness):
    return _tec.TC_SetLEDBrightness(serialNo, brightness)

def TC_RequestCurrentLimit(serialNo):
    return _tec.TC_RequestCurrentLimit(serialNo)

def TC_GetCurrentLimit(serialNo):
    return _tec.TC_GetCurrentLimit(serialNo)

def TC_SetCurrentLimit(serialNo, maxCurrent):
    return _tec.TC_SetCurrentLimit(serialNo, maxCurrent)

def TC_RequestSensorType(serialNo):
    return _tec.TC_RequestSensorType(serialNo)

def TC_GetSensorType(serialNo):
    return _tec.TC_GetSensorType(serialNo)

def TC_SetSensorType(serialNo, sensor):
    return _tec.TC_SetSensorType(serialNo, sensor)

def TC_RequestTempLoopParams(serialNo):
    return _tec.TC_RequestTempLoopParams(serialNo)

def TC_GetTempLoopParams(serialNo, proportionalIntegralDerivativeParams):
    return _tec.TC_GetTempLoopParams(serialNo, proportionalIntegralDerivativeParams)

def TC_SetTempLoopParams(serialNo, proportionalIntegralDerivativeParams):
    return _tec.TC_SetTempLoopParams(serialNo, proportionalIntegralDerivativeParams)

def TC_RequestStatus(serialNo):
    return _tec.TC_RequestStatus(serialNo)

def TC_RequestReadings(serialNo):
    return _tec.TC_RequestReadings(serialNo)

def TC_RequestStatusBits(serialNo):
    return _tec.TC_RequestStatusBits(serialNo)

def TC_GetTemperatureReading(serialNo):
    return _tec.TC_GetTemperatureReading(serialNo)

def TC_GetCurrentReading(serialNo):
    return _tec.TC_GetCurrentReading(serialNo)

def TC_GetStatusBits(serialNo):
    return _tec.TC_GetStatusBits(serialNo)

def TC_StartPolling(serialNo, milliseconds):
    return _tec.TC_StartPolling(serialNo, milliseconds)

def TC_PollingDuration(serialNo):
    return _tec.TC_PollingDuration(serialNo)

def TC_StopPolling(serialNo):
    return _tec.TC_StopPolling(serialNo)

def TC_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS):
    return _tec.TC_TimeSinceLastMsgReceived(serialNo, lastUpdateTimeMS)

def TC_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout):
    return _tec.TC_EnableLastMsgTimer(serialNo, enable, lastMsgTimeout)

def TC_HasLastMsgTimerOverrun(serialNo):
    return _tec.TC_HasLastMsgTimerOverrun(serialNo)

def TC_RequestSettings(serialNo):
    return _tec.TC_RequestSettings(serialNo)

